### ISSUE TITLE
Depends on very old grunt version

### ISSUE THREAD

**Issue by jrbenito** [mllrsohn/grunt-invalidate-cloudfront#16]
Hi there, 

Please make it depends on newer Grunt.

Thanks

**Comment by mareksuscak** [comment]
[Relevant PR](https://github.com/mllrsohn/grunt-invalidate-cloudfront/pull/15) has been merged recently. Just wasn't released yet. You could try to move to [scoped fork](https://www.npmjs.com/package/@jwalsh/grunt-invalidate-cloudfront) meanwhile. [Here's](https://docs.npmjs.com/getting-started/scoped-packages#using-a-scoped-package) how you reference it in the package.json.

**Comment by steffenmllr** [comment]
Sorry about the delay, I've published 1.0
